<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="svnindex.xsl"?>
<!DOCTYPE svn [
  <!ELEMENT svn   (index)>
  <!ATTLIST svn   version CDATA #REQUIRED
                  href    CDATA #REQUIRED>
  <!ELEMENT index (updir?, (file | dir)*)>
  <!ATTLIST index name    CDATA #IMPLIED
                  path    CDATA #IMPLIED
                  rev     CDATA #IMPLIED>
  <!ELEMENT updir EMPTY>
  <!ELEMENT file  (prop)*>
  <!ATTLIST file  name    CDATA #REQUIRED
                  href    CDATA #REQUIRED>
  <!ELEMENT dir   (prop)*>
  <!ATTLIST dir   name    CDATA #REQUIRED
                  href    CDATA #REQUIRED>
  <!ELEMENT prop  (#PCDATA)>
  <!ATTLIST prop  name    CDATA #REQUIRED>
]>
<svn version="1.2.3 (r15833)"
     href="http://subversion.tigris.org/">
  <index rev="8451" path="/trunk">
    <updir />
    <dir name="apps" href="apps/"></dir>
    <dir name="contrib" href="contrib/"></dir>
    <dir name="docs" href="docs/"></dir>
    <dir name="freenet" href="freenet/"></dir>
    <dir name="plugins" href="plugins/"></dir>
    <dir name="website" href="website/"></dir>
    <dir name="win32-bin" href="win32-bin/"></dir>
  </index>
</svn>
